### ISSUE TITLE
FSCAN fails after ESP-IDF migration.

### ISSUE THREAD

**Issue by tschak909** [FujiNetWIFI/fujinet-tools#3]
FSCAN does not return results, console window emits the following, on run:

```
11:55:52.881 > Fuji cmd: SCAN NETWORKS
11:55:52.881 > W (466725) wifi:sta_scan: STA is connecting, scan are not allowed!
11:55:52.881 > esp_wifi_scan_start returned error -1
11:55:52.881 > W (466725) wifi:sta_scan: STA is connecting, scan are not allowed!
11:55:52.885 > esp_wifi_scan_start returned error -1
11:55:52.885 > W (466735) wifi:sta_scan: STA is connecting, scan are not allowed!
11:55:52.885 > esp_wifi_scan_start returned error -1
11:55:52.885 > W (466735) wifi:sta_scan: STA is connecting, scan are not allowed!
11:55:52.885 > esp_wifi_scan_start returned error -1
11:55:52.885 > W (466735) wifi:sta_scan: STA is connecting, scan are not allowed!
11:55:52.888 > esp_wifi_scan_start returned error -1
11:55:52.888 > W (466735) wifi:sta_scan: STA is connecting, scan are not allowed!
11:55:52.888 > esp_wifi_scan_start returned error -1
11:55:52.888 > esp_wifi_scan returned 0
11:55:52.888 > COMPLETE!
```

To reproduce
=========
1. Boot a DOS with FNC tools
2. Run FSCAN

What should happen
==============
List of networks should be returned.

**Comment by kaelef** [comment]
This was likely a timing issue introduced by the auto-wifi-reconnect feature.  FN was in an endless loop trying to re-connect to its last valid WiFi network, and scans are not allowed in this state. Changed behavior to only attempt reconnect if an SSID exists in fnconfig.ini and the loop is limited to 8 retries.

**Comment by kaelef** [comment]
Well never mind... The timing thing was indeed an issue for certain situations for A8 config, but you also apparently can't scan while connected.  Added code to disconnect/scan/reconnect as needed.  Of course, this means any established TCP connections will be interrupted/broken when a scan happens.
