### ISSUE TITLE
fls SIO error

### ISSUE THREAD

**Issue by a8bit** [FujiNetWIFI/fujinet-tools#4]
I noticed this morning (while I was fighting with ICE-T) that fls returns an SIO error on host #1, that's my SD host. It returns a dir listing for the other hosts. I've not done any extensive testing, just noticed in passing.

**Comment by tschak909** [comment]
Awesome, can you launch the flasher and press Monitor, then do an fls on
your SD slot? I can debug from that. :)
-Thom

**Comment by a8bit** [comment]
PEBKAC

It helps if the SD card is in the Fujinet, not in the Mac!
