### ISSUE TITLE
Non-command-line invocation of FLS should prompt before exit

### ISSUE THREAD

**Issue by billkendrick** [FujiNetWIFI/fujinet-tools#5]
When running `FLH.COM` (list hosts) from a menu-based DOS like MyDOS, after the listing appears, you are prompted to press `[RETURN]` to continue, at which point the program returns to the MyDOS menu (which clears the screen).

The `FLS.COM` (list files in a slot) does not do this, so after the listing appears it is immediately erased by the DOS menu. It should act the same.

**Comment by jellonek** [comment]
The question is - for which doses it should be done? FLS does that only for mydos, while IMO this could be also useful for ataridos (which in most cases is probably used with dup.sys, while there are available command line CPs for it).

**Comment by jellonek** [comment]
NVM, I see that it can be done in a better way than as in FLH.
