### ISSUE TITLE
Enhance NCOPY to support wildcards.

### ISSUE THREAD

**Issue by tschak909** [FujiNetWIFI/fujinet-tools#8]
NCOPY needs to be extended to support wildcards.

This is accomplished by:

* Detecting wildcards in string (* and ?)
* Using wildcards to open N: device 4 (0x74) with directory mode (aux1=6)
* Read each entry into a list
* Pass each returned entry into the appropriate ncopy subroutine (d to n, n to d, or n to n), displaying filename. until done.

The filename translation mode used depends on whether it is D to N, N to D, or N to N:

* For D to N or N to D, 8.3 filename translation should be used, and thus aux2 = 0.
* For N to N, full filename translation should be used, and thus aux2 = 128

Since Aux2=0 provides a DOS 2 compatible directory output, the translation routine needs to convert

```
FILE    TXT 012
```

to: 
```
FILE.TXT
 ```

For aux2=128, the filename can be used as is. 

NCOPY is here:
https://github.com/FujiNetWIFI/fujinet-config-tools/tree/master/ncopy

**Comment by jellonek** [comment]
IMO the procedure should be changed a bit to something like:
* expand the source string (if it has or not wildcard chars) to a list of source items
* if expanded list is empty - show an error message and exit
* if it is expanded to more than one entry - check if the destination is a directory. if not - return an error message and exit
* iterate over expanded list copying entries to destination place

Expansion to the list could be done by:
* split source string to device, list of directories patterns, file pattern.
* make empty list of final source directories. if list of directories patterns is empty fill it with a single empty entry (this will be pointing to the root dir of dev), else generate list of matched subdirs (described below)
* make empty output source files list
* iterate over produced list of source directories calling "match files" in each of them, appending resulting matches to freshly created output source files list
* return it

Subdirs matcher could be done as a func which is getting device name, base prefix, list of directories patterns which should call self recursively in a way:
* if list of directories patterns is empty - just return nothing
* make empty list of output directories
* open directory (base prefix, empty in first call) for given device and base prefix,
* match found directories against first entry in the provided list of directories patterns. if entry matches the patterns and the list of patterns is bigger than one call recursively self with base prefix extended with matched entry. append output of this call to the list of output directories. if the list of remaining patterns was empty - return a single element list with device:\prefix

"match files" should have as an input list of dirs and on each of them it should call dir, then proceed with matching an entry with a pattern, returning list of matched items.

**Comment by tschak909** [comment]
First pass of this has been checked in.
